@startuml
title Sequence diagram (Processo di login) - Iterazione 2

actor User as U
participant "Frontend"          as FE
participant "API Gateway"       as GW
participant "Auth Controller"   as AC
participant "Auth Service"      as AS
participant "Profile Repository" as PR
participant "MongoDB"           as DB
participant "JWT Manager"       as JWT

U  -> FE  : Inserisce credenziali
FE -> GW  : POST /login
GW -> AC  : Login
AC -> AS  : Autenticazione
AS -> PR  : Cerca utente per matricola
PR -> DB  : query
DB --> PR : user data
PR --> AS : User
AS -> JWT : Generazione token 
JWT --> AS : JWT
AS --> AC : token
AC --> GW : token
GW --> FE : token

@enduml